export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_DELIVERY = "UPDATE_DELIVERY";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const RESET_CHECKOUT = "RESET_CHECKOUT";
